theme: jekyll-theme-hacker
title: Carlos Ramirez CS-499 ePortfolio
description: This is my final Portfolio which demonstrates all the skills I have acquired in the computer science program, shown explicitly in three categories: Software design and engineering, Algorithms and data structure, and Databases
